### ISSUE TITLE
__WORDSIZE is undefined

### ISSUE THREAD

**Issue by zecode** [dennis714/octothorpe#2]
In short, I noticed 'AM_PROG_AR not found' warning, then 'error __WORDSIZE is undefined', then fixed it.

I followed INSTALL.md and setup mingw64 x86_64-4.8.5-win32-seh-rt_v4-rev0 http://sourceforge.net/projects/mingw-w64/files/ and msys http://sourceforge.net/projects/mingw/files/ on Windows 7 x64.

First, in cmd: git clone https://github.com/dennis714/octothorpe octo4.8
Then in msys:

ze@ze-pc /q/code/yu/octo4.8
$ autoreconf --install
configure.ac:8: warning: macro `AM_PROG_AR' not found in library
configure.ac:8: error: possibly undefined macro: AM_PROG_AR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf-2.68 failed with exit status: 1

ze@ze-pc /q/code/yu/octo4.8
$ autoreconf --install
configure.ac:8: warning: macro `AM_PROG_AR' not found in library
configure.ac:2: installing `./install-sh'
configure.ac:2: installing `./missing'
lib/Makefile.am: installing `./depcomp'

ze@ze-pc /q/code/yu/octo4.8
$ mkdir build

ze@ze-pc /q/code/yu/octo4.8
$ cd build/

ze@ze-pc /q/code/yu/octo4.8/build
$ ../configure
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
../configure: line 3789: AM_PROG_AR: command not found
checking for stricmp... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of size_t... 8
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating include/Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands

ze@ze-pc /q/code/yu/octo4.8/build
$ make
make  all-recursive
make[1]: Entering directory `/q/code/yu/octo4.8/build'
Making all in lib
make[2]: Entering directory `/q/code/yu/octo4.8/build/lib'
gcc -DHAVE_CONFIG_H -I. -I../../lib -I..  -I../../include   -Wall -std=c11 -mlzc
nt -O3 -MT FPU_stuff_GCC.o -MD -MP -MF .deps/FPU_stuff_GCC.Tpo -c -o FPU_stuff_G
CC.o ../../lib/FPU_stuff_GCC.c
In file included from ../../include/FPU_stuff.h:20:0,
                 from ../../lib/FPU_stuff_GCC.c:18:
../../include/datatypes.h:59:2: error: #error "__WORDSIZE is undefined"
 #error "__WORDSIZE is undefined"
  ^
make[2]: *** [FPU_stuff_GCC.o] Error 1
make[2]: Leaving directory `/q/code/yu/octo4.8/build/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/q/code/yu/octo4.8/build'
make: *** [all] Error 2

ze@ze-pc /q/code/yu/octo4.8/build

Ok, I tried to change a line in configure.ac 
CFLAGS="-Wall -std=c11 -mlzcnt"
to
CFLAGS="-Wall -std=c11 -mlzcnt -D__WORDSIZE=64"
then again autoreconf, configure, and make succeeded! make check PASS as well!

Is it a correct way to build the project?

**Comment by dennis714** [comment]
Oh yes, I haven't used MinGW for ages. Don't know if it compiles at all. Maybe I'll fix this at some point in future.

**Comment by zecode** [comment]
I have problems with compiling 'tracer'. Is it still possible to build it on Windows?

I managed to make octothorp (with -D__WORDSIZE=64 fix). make check. make install.

Then I make porg (also with -D__WORDSIZE=64 fix). Although make check failed:
gcc  -Wall -std=c11 -D__WORDSIZE=64 -I/usr/local/include/octothorpe -O3  -L/usr/
local/lib -o test1.exe test1.o ../lib/libporg.a -lpsapi -limagehlp -loctothorpe

../lib/libporg.a(porg_utils.o):porg_utils.c:(.text+0x681): undefined reference t
o `obj_tetrabyte'
collect2.exe: error: ld returned 1 exit status

Next, attempt to make x86_disasm. Again, defined __WORDSIZE in configure.ac
Besides that, I had to edit include/x86_disas_internals.h and add
#define OCTABYTE_1 ((uint64_t)1)
(otherwise make error OCTABYTE_1 undefined)
Then I replaced OBJ_TETRABYTE with OBJ_TETRA and OBJ_OCTABYTE with OBJ_OCTA in lib/X86_register.c
make succeeded, make check failed
gcc  -Wall -std=c11 -D__WORDSIZE=64 -I/usr/local/include/octothorpe -O3  -L/usr/
local/lib -o x86_disasm_tests.exe x86_disasm_tests.o ../lib/libx86_disasm.a -loc
tothorpe
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x8d9): undefined referen
ce to `obj_tetrabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x909): undefined referen
ce to `obj_tetrabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x942): undefined referen
ce to `obj_tetrabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x970): undefined referen
ce to `obj_tetrabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x9b7): undefined referen
ce to `obj_tetrabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x9fa): undefined referen
ce to `obj_octabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0xa2a): undefined referen
ce to `obj_octabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0xa5e): undefined referen
ce to `obj_octabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0xa7e): undefined referen
ce to `obj_octabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0xab7): undefined referen
ce to `obj_octabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0xaf1): more undefined re
ferences to `obj_octabyte2' follow
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0xd06): undefined referen
ce to `obj_tetrabyte2'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x5d95): undefined refere
nce to `zero_extend_to_octabyte'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x6008): undefined refere
nce to `zero_extend_to_octabyte'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x63e7): undefined refere
nce to `zero_extend_to_octabyte'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x9137): undefined refere
nce to `obj_get_as_tetrabyte'
../lib/libx86_disasm.a(x86_disas.o):x86_disas.c:(.text+0x917a): undefined refere
nce to `obj_get_as_tetrabyte'
collect2.exe: error: ld returned 1 exit status

I'm trying to make first steps in reversing world after 10+ dev xp (business java, java games server, .net servers and clients, python, network protocols reversing, web).
I used c very occasionally. So, c/c++ stack/build tools are not familiar to me.
Probably, I should try to crosscompile to Windows from linux.
Could you please direct me?

**Comment by dennis714** [comment]
My tracer tool is also unmaintained and buggy. Don't bother with it. If you want to make "first steps", just use debugger, like OllyDbg.
